default_context:
  project_name: 'MoneyTree'
  project_slug: 'mt'
  domain_main: 'moneytree.gusgewehr.com'
  domain_staging: 'stag.moneytree.gusgewehr.com'
  docker_swarm_stack_name_main: 'moneytree-gusgewehr-com'
  docker_swarm_stack_name_staging: 'stag-moneytree-gusgewehr-com'
  secret_key: 'd9e0d6dfc12f8a3c41ab31c74ac75b4b'
  first_superuser: 'gusgewehr'
  first_superuser_password: 'Gewehr/1025/12'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.moneytree.gusgewehr.com", "https://stag.moneytree.gusgewehr.com", "https://moneytree.gusgewehr.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@moneytree.gusgewehr.com'
  postgres_password: 'Gewehr/1025/12'
  pgadmin_default_user: 'gusgewehr'
  pgadmin_default_user_password: 'Gewehr/1025/12'
  traefik_constraint_tag: 'moneytree.gusgewehr.com'
  traefik_constraint_tag_staging: 'stag.moneytree.gusgewehr.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Gewehr/1025/12'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
